### PR TITLE
add the orc test support in oap-perf-suite

### PR DESCRIPTION
**Pull request by JkSelf**
add  orc support test .

### CODE REVIEW

**Comment by JkSelf** [comment]
@carsonwang please help review and merge. Thanks.

**Comment by carsonwang** [comment]
@JkSelf, I am not familiar with this project and I think you can merge it yourself directly. Do you have the merging permission?

**Comment by JkSelf** [comment]
@carsonwang I have no the permission.

**Comment by JkSelf** [comment]
Have tested and merged.

**Pull request merged**
